version: "3.7"

services:
  database_popcorn:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    container_name: database_popcorn
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=popcorntv
      - MYSQL_ROOT_PASSWORD=test
    volumes:
      - mysqldata:/data/mysql
  app:
    build: .
    container_name: popcorntv-backend
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_popcorn
    depends_on:
      - database_popcorn

volumes:
  mysqldata:
    driver: local
